# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
