# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

# WSL2
env:
  GOOS: windows

tasks:
  tidy:
    desc: 更新依赖 (运行go mod tidy)
    cmds:
      - go mod tidy

  build:
    desc: 构建
    sources:
      - ./**/*.go
    generates:
      - "./dowserC.exe"
    cmd: go build -o dowserC.exe {{ .CLI_ARGS }} .

  test:
    desc: 运行测试
    vars:
      SOURCE_FILES: '{{default "./..." .SOURCE_FILES}}'
      TEST_PATTERN: '{{default "." .TEST_PATTERN}}'
    cmd: go test {{ .CLI_ARGS }} -failfast {{ .SOURCE_FILES }} -run {{ .TEST_PATTERN }} -timeout=5m

  lint:
    desc: 使用 golangci-lint 检查代码
    cmd: golangci-lint run --config ./.golangci.yaml {{.CLI_ARGS}} ./...

  fmt:
    desc: 使用 gofumpt 格式化代码
    vars:
      FILES: '{{default "." .FILES}}'
    cmd: gofumpt -w -l {{ .FILES }}

  ci:
    desc: 运行CI
    cmds:
      - task: setup
      - task: build
      - task: test

  default:
    desc: 运行CI
    cmds:
      - task: ci

  release:
    desc: 发布新版本
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin --tags
