# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 创建发行版

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: 运行 goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --timeout=90m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
